version: '3.8'

services: 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./web
    restart: always
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://bloguser:blogpassword@db:3306/blogdb
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
